const { Job } = require("../models");

const JobData = async () => {
  try {
    const insertRecords = [
      {
        jobTitle: "Full Stack Developer",
        jobLocation: "On-site",
        employerId: "43",
        specificCity: "New York",
        advertiseCity: "Yes",
        city: "New York",
        state: "Dsadsasa",
        area: "Manhattan",
        pincode: "10001",
        streetAddress: "123 Main Street",
        jobTypes: ["Full-time", "Permanent"],
        education: ["10", "12"],
        skills: ["react", "node"],
        languages: ["hindi", "english"],
        minimumPay: "50000",
        maximumPay: "80000",
        payType: "Range",
        exactPay: null,
        payRate: "per year",
        jobDescription: "Seeking a skilled full stack developer...",
        numberOfPeople: "2",
        mobileNumber: "1234567890",
        email: "example@example.com",
        deadline: "No",
        deadlineDate: null,
        status: "Open",
        experience: "1 year",
        createdAt: "2024-07-18 09:11:09",
        updatedAt: "2024-07-18 09:11:09",
        employeeId: null,
      },
      {
        jobTitle: "Backend Engineer",
        jobLocation: "Remote",
        employerId: "43",
        specificCity: null,
        advertiseCity: "No",
        city: "San Francisco",
        state: "Dsadsasa",
        area: "Bay Area",
        pincode: "94105",
        streetAddress: "456 Market Street",
        jobTypes: ["Full-time"],
        education: ["10", "12"],
        skills: ["react", "node"],
        languages: ["hindi", "english"],
        minimumPay: null,
        maximumPay: null,
        payType: "Exact amount",
        exactPay: "70000",
        payRate: "per year",
        jobDescription: "Backend engineer needed to build scalable APIs...",
        numberOfPeople: "1",
        mobileNumber: "9876543210",
        email: "another@example.com",
        deadline: "Yes",
        deadlineDate: "2024-12-31",
        status: "Open",
        experience: "1 year",
        createdAt: "2024-07-18 09:11:09",
        updatedAt: "2024-07-18 09:11:09",
        employeeId: null,
      },
      {
        jobTitle: "UI/UX Designer",
        jobLocation: "On-site",
        employerId: "43",
        specificCity: "Los Angeles",
        advertiseCity: "Yes",
        city: "Los Angeles",
        state: "Dsadsasa",
        area: "Downtown",
        pincode: "90001",
        streetAddress: "789 Broadway",
        jobTypes: ["Full-time", "Temporary"],
        education: ["10", "12"],
        skills: ["react", "node", "xyz"],
        languages: ["hindi", "english"],
        minimumPay: "60000",
        maximumPay: "90000",
        payType: "Range",
        exactPay: null,
        payRate: "per year",
        jobDescription:
          "Looking for a creative UI/UX designer to join our team...",
        numberOfPeople: "1",
        mobileNumber: "5556667777",
        email: "designer@example.com",
        deadline: "No",
        deadlineDate: null,
        status: "Open",
        experience: "1 year",
        createdAt: "2024-07-18 09:11:09",
        updatedAt: "2024-07-18 09:11:09",
        employeeId: null,
      },
      {
        jobTitle: "React js developer",
        jobLocation: "Remote",
        employerId: "44",
        specificCity: "",
        advertiseCity: "No",
        city: "",
        state: "",
        area: "",
        pincode: "",
        streetAddress: "",
        jobTypes: ["Full-time", "Internship", "Temporary"],
        education: ["ssc"],
        skills: ["react js"],
        languages: ["english"],
        minimumPay: "34535",
        maximumPay: "234234",
        payType: "Range",
        exactPay: "",
        payRate: "per year",
        jobDescription: "<ul><li>hello</li></ul>",
        numberOfPeople: "2",
        mobileNumber: "8569856325",
        email: "tester02@gmail.com",
        deadline: "No",
        deadlineDate: "",
        status: "Open",
        experience: "1 Year",
        createdAt: "2024-07-19 04:48:33",
        updatedAt: "2024-07-19 04:48:33",
        employeeId: null,
      },
      {
        jobTitle: "Human resources generalist",
        jobLocation: "Remote",
        employerId: "44",
        specificCity: "",
        advertiseCity: "No",
        city: "",
        state: "",
        area: "",
        pincode: "",
        streetAddress: "",
        jobTypes: ["Full-time", "Internship", "Temporary"],
        education: ["ssc"],
        skills: ["react js"],
        languages: ["english"],
        minimumPay: "34535",
        maximumPay: "234234",
        payType: "Range",
        exactPay: "",
        payRate: "per year",
        jobDescription: "<p>hello</p>",
        numberOfPeople: "2",
        mobileNumber: "8569856325",
        email: "tester02@gmail.com",
        deadline: "No",
        deadlineDate: "NaN-NaN-NaN",
        status: "Open",
        experience: "1 Year",
        createdAt: "2024-07-19 04:48:59",
        updatedAt: "2024-07-19 04:48:59",
        employeeId: null,
      },
      {
        jobTitle: "Next js developer",
        jobLocation: "Remote",
        employerId: "44",
        specificCity: "",
        advertiseCity: "No",
        city: "",
        state: "",
        area: "",
        pincode: "",
        streetAddress: "",
        jobTypes: ["Full-time", "Internship", "Temporary"],
        education: ["ssc"],
        skills: ["react js"],
        languages: ["english"],
        minimumPay: "34535",
        maximumPay: "234234",
        payType: "Range",
        exactPay: "",
        payRate: "per year",
        jobDescription: "<ul><li>hello</li></ul>",
        numberOfPeople: "2",
        mobileNumber: "8569856325",
        email: "tester02@gmail.com",
        deadline: "No",
        deadlineDate: "NaN-NaN-NaN",
        status: "Open",
        experience: "1 Year",
        createdAt: "2024-07-19 04:49:17",
        updatedAt: "2024-07-19 04:49:17",
        employeeId: null,
      },
    ];
    await Job.bulkCreate(insertRecords);
  } catch (error) {
    console.log("Coupon seeder:", error);
  }
};

module.exports = { JobData };
